//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotGES {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class nnet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nnet() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VotGES.nnet", typeof(nnet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a:7:{s:3:&quot;l1c&quot;;a:39:{i:0;a:2:{i:0;d:2010;i:1;d:3.5;}i:1;a:2:{i:0;d:183;i:1;d:183;}i:2;a:2:{i:0;d:-0.52;i:1;d:31.5;}i:3;a:2:{i:0;d:87.1;i:1;d:1.96;}i:4;a:2:{i:0;d:87.1;i:1;d:1.96;}i:5;a:2:{i:0;d:87.1;i:1;d:1.96;}i:6;a:2:{i:0;d:87.1;i:1;d:1.96;}i:7;a:2:{i:0;d:3740;i:1;d:3740;}i:8;a:2:{i:0;d:3740;i:1;d:3740;}i:9;a:2:{i:0;d:3740;i:1;d:3740;}i:10;a:2:{i:0;d:3740;i:1;d:3740;}i:11;a:2:{i:0;d:3740;i:1;d:3740;}i:12;a:2:{i:0;d:3740;i:1;d:3740;}i:13;a:2:{i:0;d:3740;i:1;d:3740;}i:14;a:2:{i:0;d:3740;i:1;d:3740;}i:15;a:2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string vges_nb {
            get {
                return ResourceManager.GetString("vges_nb", resourceCulture);
            }
        }
    }
}
